# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'scout_project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '8.0'

  # Pods for scout_project
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga' # <-- uncomment to solve Yoga error
  pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  target 'scout_project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scout_projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'scout_project-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for scout_project-tvOS

  #target 'scout_project-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
